// <auto-generated />
namespace WebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_LoginMsgError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_LoginMsgError));
        
        string IMigrationMetadata.Id
        {
            get { return "202101130326361_add_LoginMsgError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
